name: Deploy Node Server

on:
  push:
    branches:
      - develop
    paths:
      - 'server/**'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # 部署到预发环境
      - name: Deploy To Pre
        uses: appleboy/ssh-action@v1.1.0
        with:
          host: '${{ secrets.PRE_SERVER_HOST }}'
          username: ${{ secrets.PRE_SERVER_NAME }}
          key: ${{ secrets.PRE_SERVER_SSH_KEY }}
          script: |
            echo 'Set Environment Variable'
            export SESSION_SECRET="${{ secrets.SESSION_SECRET }}"

            echo 'Update Code'
            cd ~/apps/noa/packages/noa-server/
            git reset --hard
            git pull

            echo 'Install Dependence & Build'
            pnpm i
            pnpm build

            echo 'Reload Server'
            pm2 startOrReload --wait-ready ecosystem.config.js
